# -*- encoding: utf-8 -*-
require File.expand_path('../lib/sentient_user/version.rb', __FILE__)

Gem::Specification.new do |gem|
  gem.authors       = ["bokmann"]
  gem.email         = ["dbock@codesherpas.com"]
  gem.description   = %q{lets the User model in most authentication frameworks know who is the current user}
  gem.summary       = %q{A trivial bit of common code}
  gem.homepage      = "http://github.com/bokmann/sentient_user"

  gem.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  gem.files         = `git ls-files`.split("\n")
  gem.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  gem.name          = "font-awesome-rails"
  gem.require_paths = ["lib"]
  gem.version       = SentientUser::VERSION

  gem.add_dependency "railties", "~> 3.1"
  gem.add_development_dependency "rake"
  gem.add_development_dependency "shoulda", ">= 2.11.3"

end




# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
#
# Gem::Specification.new do |s|
#   s.name = %q{sentient_user}
#   s.version = "0.3.2"
#
#   s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
#   s.authors = ["bokmann"]
#   s.date = %q{2011-01-17}
#   s.description = %q{lets the User model in most authentication frameworks know who is the current user"}
#   s.email = %q{dbock@codesherpas.com}
#   s.extra_rdoc_files = [
#     "LICENSE",
#     "README.rdoc"
#   ]
#   s.files = [
#     ".document",
#     "LICENSE",
#     "README.rdoc",
#     "Rakefile",
#     "VERSION",
#     "lib/sentient_user.rb",
#     "sentient_user.gemspec",
#     "test/helper.rb",
#     "test/test_sentient_user.rb"
#   ]
#   s.homepage = %q{http://github.com/bokmann/sentient_user}
#   s.require_paths = ["lib"]
#   s.rubygems_version = %q{1.3.7}
#   s.summary = %q{A trivial bit of common code}
#   s.test_files = [
#     "test/helper.rb",
#     "test/test_sentient_user.rb"
#   ]
#
#   if s.respond_to? :specification_version then
#     current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
#     s.specification_version = 3
#
#     if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
#       s.add_development_dependency(%q<shoulda>, [">= 2.11.3"])
#     else
#       s.add_dependency(%q<shoulda>, [">= 2.11.3"])
#     end
#   else
#     s.add_dependency(%q<shoulda>, [">= 2.11.3"])
#   end
# end

